// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlataformaEducacional.FinancialManagement.Data;

#nullable disable

namespace PlataformaEducacional.FinancialManagement.Data.Migrations
{
    [DbContext(typeof(PaymentContext))]
    partial class PaymentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("PlataformaEducacional.FinancialManagement.Core.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacional.FinancialManagement.Core.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacional.FinancialManagement.Core.Payment", b =>
                {
                    b.OwnsOne("PlataformaEducacional.FinancialManagement.Core.CardData", "CardData", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CardCvv")
                                .IsRequired()
                                .HasColumnType("varchar(4)")
                                .HasColumnName("CardCvv");

                            b1.Property<string>("CardExpiration")
                                .IsRequired()
                                .HasColumnType("varchar(10)")
                                .HasColumnName("CardExpiration");

                            b1.Property<string>("CardNumber")
                                .IsRequired()
                                .HasColumnType("varchar(16)")
                                .HasColumnName("CardNumber");

                            b1.Property<string>("CardholderName")
                                .IsRequired()
                                .HasColumnType("varchar(250)")
                                .HasColumnName("CardholderName");

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("CardData")
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaEducacional.FinancialManagement.Core.Transaction", b =>
                {
                    b.HasOne("PlataformaEducacional.FinancialManagement.Core.Payment", "Payment")
                        .WithOne("Transaction")
                        .HasForeignKey("PlataformaEducacional.FinancialManagement.Core.Transaction", "PaymentId")
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("PlataformaEducacional.FinancialManagement.Core.Payment", b =>
                {
                    b.Navigation("Transaction")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
